customhost = "employee.c5w84m4wmd55.ap-southeast-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "test1234"
customdb = "employee"
custombucket = "mys3bucket00335"
customregion = "ap-southeast-1"
